project: {type: website, output-dir: docs}
website:
  title: 'SciNoj Light #1'
  navbar:
    search: true
    left:
    - {href: index.qmd, text: Home}
    - speakers.qmd
    - hosts.qmd
format:
  html: {theme: flatly, linkcolor: '#440044', toc: true}
